name: Build MPGA C-OS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cmake .
      
    - name: Make
      run: make
      
    - name: Test
      run: ctest --output-on-failure

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: c-os
        path: c-os
        if-no-files-found: error