name: Build MPGA C-OS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          cmake
          ninja
          make

    # Linux/macOS 步骤保持不变
    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build
    
    - name: Configure CMake
      run: cmake -G Ninja .
      
    - name: Build C-OS
      run: ninja
      
    - name: Test output
      run: ctest --output-on-failure

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: c-os-${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}
        path: c-os*
        if-no-files-found: error