name: Build MPGA C-OS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        Invoke-WebRequest -Uri https://cmake.org/files/v3.28/cmake-3.28.0-windows-x86_64.msi -OutFile cmake.msi
        Start-Process -FilePath msiexec -ArgumentList "/i cmake.msi /quiet ADD_CMAKE_TO_PATH=System" -Wait
        choco install ninja -y
        refreshenv
    
    - name: Configure CMake
      run: cmake -G "${{ matrix.os == 'windows-latest' && 'Ninja' || 'Unix Makefiles' }}" .
      
    - name: Build C-OS
      run: ${{ matrix.os == 'windows-latest' && 'ninja' || 'make -j$(nproc)' }}
      
    - name: Test output
      run: ctest --output-on-failure

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: c-os-${{ matrix.os }}
        path: c-os*
        if-no-files-found: error