name: Build MPGA C-OS

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cmake .
      
    - name: Make
      run: make
      
    - name: Test
      run: ctest --output-on-failure

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: c-os
        path: |
          c-os
          c-os.*
      if-no-files-found: error